compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  kitsuned:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${NPM_AUTH_TOKEN}"
