[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[features]
sandbox = []

[profile.release]
lto = true
strip = true
opt-level = "z"

[dependencies]
mnt = "0.3.1"
nix = { version = "0.26.2", features = ["mount"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
